package com.csye6225.fall2018.project.jw.cloudProject.datamodel;

import java.util.List;
import java.util.Set;

import org.joda.time.format.PeriodFormat;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIgnore;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.csye6225.fall2018.project.jw.cloudProject.service.ProfessorService;
 


@DynamoDBTable(tableName="course")
public class Course {
	
	/**
	 - Id (Dynamo Db generated) and hash key
     - courseId - DynamoDbIndexHashKey, a Global Secondary Index (GSI)
     - professorId
     - taId
     - department
     - boardId
     - listOfRegisteredStudents/roster - has student Id list (this is the roster)
	 */
	private String id;
	private String courseId;
	private String boardId;
	private String name;
	private String professorId;
	private String taId;
	private String department;
	
	private Set<String> roster;
	private Set<String> lectures;
	private String  snsTopic;// - notificationTopic // NEW FIELD for storing sns topic. 
	
	
	//private List<Student> enrolledStudents;
	public Course() {
	}
	
	public Course(String name, String courseId, String professorId, String department) {
		this.courseId = courseId;
		this.name = name;
		this.professorId = professorId;
		this.department = department;
	}

	
	@DynamoDBHashKey(attributeName = "id")
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}

    @DynamoDBIndexHashKey(attributeName = "courseId", globalSecondaryIndexName = "courseId-index")
	public String getCourseId() {
		return courseId;
	}
	public void setCourseId(String courseId) {
		this.courseId = courseId;
	}

   // @DynamoDBIndexHashKey(attributeName = "boardId", globalSecondaryIndexName = "boardId-index")
	@DynamoDBAttribute(attributeName = "boardId")
	public String getBoardId() {
		return boardId;
	}
	public void setBoardId(String boardId) {
		this.boardId = boardId;
	}
	
    @DynamoDBIndexHashKey(attributeName = "professorId", globalSecondaryIndexName = "professorId-index")
	public String getProfessorId() {
		return professorId;
	}
	public void setProfessorId(String professorId) {
		this.professorId = professorId;
	}

    @DynamoDBIndexHashKey(attributeName = "departmentId", globalSecondaryIndexName = "departmentId-index")
	public String getDepartment() {
		return department;
	}
	public void setDepartment(String department) {
		this.department = department;
	}

	@DynamoDBAttribute(attributeName = "taId")
	public String getTaId() {
		return taId;
	}
	public void setTaId(String taId) {
		this.taId = taId;
	}

	@DynamoDBAttribute(attributeName = "roster")
	public Set<String> getRoster() {
		return roster;
	}
	public void setRoster(Set<String> roster) {
		this.roster = roster;
	}

	@DynamoDBAttribute(attributeName = "lectures")
	public Set<String> getLectures() {
		return lectures;
	}
	public void setLectures(Set<String> lectures) {
		this.lectures = lectures;
	}

	@DynamoDBAttribute(attributeName = "name")
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	
	
	@DynamoDBAttribute(attributeName = "snsTopic")
	public String getSnsTopic() {
		return snsTopic;
	}

	public void setSnsTopic(String snsTopic) {
		this.snsTopic = snsTopic;
	}
	
	
	@Override
	public String toString() {
		/**
		 * 	private String id;
	private String courseId;
	private String boardId;
	private String name;
	private String professorId;
	private String taId;
	private String department;
	
	private Set<String> roster;
	private Set<String> lectures;
	private String  snsTopic;
		 */
		String res = "id:" +id+ "   courseId:" + courseId+ "  boardId:"+ boardId + "   name" +name
				+ "   profid" + professorId+ "   taid" +taId+ "   department" + department+ "   arn"+snsTopic 
				+ "   roster:" + roster.toString() + "  lectures:" + lectures.toString(); 
		
		return res ;
		
	}
	//
 
	


}
