package com.csye6225.fall2018.project.jw.cloudProject.datamodel;

import java.util.List;
import java.util.Set;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIgnore;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

/**
@DynamoDBHashKey(attributeName = "id")
@DynamoDBAutoGeneratedKey
@DynamoDBIndexRangeKey(attributeName = "announcementId", 	globalSecondaryIndexName = "announcementId-index")
@DynamoDBAttribute(attributeName = "announcementText")
@DynamoDBIndexHashKey(attributeName = "announcementId", globalSecondaryIndexName = "announcementId-index")
@DynamoDBIndexRangeKey(attributeName = "boardId",	globalSecondaryIndexName = "boardId-index")
 */

@DynamoDBTable(tableName="lecture")
public class Lecture {
	private String id;
	private String lectureId;
	private String notes;
	private Set<String> material;
	
	public Lecture(String notes, String lectureId) {
		this.lectureId = lectureId;
		this.notes = notes;
	}
	
	public Lecture() {
	}
	
	@DynamoDBAttribute(attributeName = "material")
	public Set<String> getMaterial() {
		return material;
	}
	public void setMaterial(Set<String> material) {
		this.material = material;
	}
	

	@DynamoDBIndexHashKey(attributeName = "lectureId", globalSecondaryIndexName = "lectureId-index")
	public String getLectureId() {
		return lectureId;
	}
	public void setLectureId(String lectureId) {
		this.lectureId = lectureId;
	}

	@DynamoDBHashKey(attributeName = "id")
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}

	@DynamoDBAttribute(attributeName = "notes")
	public String getNotes() {
		return notes;
	}
	public void setNotes(String notes) {
		this.notes = notes;
	}
	
	@DynamoDBIgnore
	@Override
	public String toString() {
		return getId() + " lectureId:" + getLectureId() + " notes:" + getNotes();
	}
	
}
