package com.csye6225.fall2018.project.jw.cloudProject.datamodel;

//import java.util.Date;
//import java.util.List;
import java.util.Set;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIgnore;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
//import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName="professor")
public class Professor {
	private String id;
	//private String name;
	private String firstName;
	private String lastName;
    private String department;
    private String professorId;
    private String joiningDate;
     
    
    @DynamoDBAttribute(attributeName = "email")
    private String email;
    
    @DynamoDBAttribute(attributeName = "courseId")
    private Set<String> courses;
    
    
    public Professor() {
    }
    
    public Professor(String professorId, String firstName, String lastName, String department, String joiningDate) {
        this.professorId = professorId;
        //this.name = name;
        //this.id = id;
        this.firstName = firstName;
        this.lastName = lastName;
        this.department = department;
        this.joiningDate = joiningDate;
    }
    
    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
    
//    @DynamoDBAttribute(attributeName = "name")
//    public String getName() {
//        return name;
//    }
//    public void setName(String name) {
//        this.name = name;
//    }
    
    //@DynamoDBAttribute(attributeName = "department")
	@DynamoDBIndexHashKey(attributeName = "department", globalSecondaryIndexName = "department-index")
    public String getDepartment() {
        return department;
    }
    public void setDepartment(String department) {
        this.department = department;
    }

    @DynamoDBIndexHashKey(attributeName = "professorId", globalSecondaryIndexName = "professorId-index")
    public String getProfessorId() {
        return professorId;
    }
    public void setProfessorId(String professorId) {
        this.professorId = professorId;
    }
    
    @DynamoDBAttribute(attributeName = "joiningDate")
    public String getJoiningDate() {
        return joiningDate;
    }
    public void setJoiningDate(String joiningDate) {
        this.joiningDate = joiningDate;
    }
	
	@DynamoDBIgnore
	@Override
	public String toString() {
		return "  proID=   " + getProfessorId()+"  ,name=" +  getFirstName() + getLastName()+ "   department:" + getDepartment()
		+ ",joindate   " + getJoiningDate();
	}

	
	
	@DynamoDBAttribute(attributeName = "firstName")
	public String getFirstName() {
		return firstName;
	}
	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}
	@DynamoDBAttribute(attributeName = "lastName")
	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}


	
}
