package com.csye6225.fall2018.project.jw.cloudProject.datamodel;

import java.util.HashSet;
import java.util.List;
import java.util.Set;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIgnore;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
 
@DynamoDBTable(tableName="program")
public class Program {
	
	private String id;
	private String programId;
	private String name;
	private Set<String> requiredCourses = new HashSet<>();
	private String department;
	
	
	public Program() {
	}
	
	public Program(String porgramId, String name, String department) {
		this.programId = porgramId;
		this.name = name;
		this.setDepartment(department);
	}

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
 
	@DynamoDBAttribute(attributeName = "name")
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}

	@DynamoDBAttribute(attributeName = "requiredCourses")
	public Set<String> getRequiredCourses() {
		return requiredCourses;
	}
	public void setRequiredCourses(Set<String> requiredCourses) {
		this.requiredCourses = requiredCourses;
	}


	@DynamoDBIndexHashKey(attributeName = "programId", globalSecondaryIndexName = "programId-index")
	public void setProgramId(String programId) {
		 this.programId = programId;
	}
	public String getProgramId() {
		return programId;
	}

	@DynamoDBIgnore
	@Override
	public String toString() {
		return "name:"+ name + " progId:" + programId + " department:" + department + " id:" + id ;
	}

	@DynamoDBIndexHashKey(attributeName = "department", globalSecondaryIndexName = "department-index")
	public String getDepartment() {
		return department;
	}
	public void setDepartment(String department) {
		this.department = department;
	}





}
