package com.csye6225.fall2018.project.jw.cloudProject.datamodel;

import javax.validation.spi.ValidationProvider;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName="register")
public class Register {
	private String id;
	private String department;
	private String offerType;
	private String offeringId;
	private String perUnitPrice;
	
	@DynamoDBHashKey(attributeName = "id")
	@DynamoDBIndexHashKey(attributeName = "id", globalSecondaryIndexName = "id-index")
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	
	@DynamoDBAttribute(attributeName = "department")
	public String getDepartment() {
		return department;
	}
	public void setDepartment(String department) {
		this.department = department;
	}
	
	@DynamoDBAttribute(attributeName = "offerType")
	public String getOfferType() {
		return offerType;
	}
	public void setOfferType(String offerType) {
		this.offerType = offerType;
	}
	
	@DynamoDBAttribute(attributeName = "offeringId")
	public String getOfferingId() {
		return offeringId;
	}
	public void setOfferingId(String offeringId) {
		this.offeringId = offeringId;
	}
	
	@DynamoDBAttribute(attributeName = "perUnitPrice")
	public String getPerUnitPrice() {
		return perUnitPrice;
	}
	public void setPerUnitPrice(String perUnitPrice) {
		this.perUnitPrice = perUnitPrice;
	}

	@Override
	public String toString() {
		return "registerID: " + id + "  department:    " + department + "  offer type: "  + offerType + "    offer id: " + 
				offeringId + "    price:" + perUnitPrice;
	}
}
