package com.csye6225.fall2018.project.jw.cloudProject.datamodel;

import java.net.URL;
import java.util.List;
import java.util.Set;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIgnore;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "student")
public class Student {

	private String id;
	private String studentId;
	private String firstName;
	private String lastName;
	private String joiningDate;
	private String department;
	private Set<String> registeredCourses;// use courseId as value

	private String image;
	private String email;
	// private URL imageURL;

	public Student() {
	}

	public Student(String studentId, String firstName, String lastName, String joiningDate, String department) {
		this.studentId = studentId;
		this.firstName = firstName;
		this.lastName = lastName;
		this.joiningDate = joiningDate;
		this.department = department;
	}

	@DynamoDBHashKey(attributeName = "id")
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@DynamoDBAttribute(attributeName = "firstName")
	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@DynamoDBAttribute(attributeName = "lastName")
	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@DynamoDBAttribute(attributeName = "joiningDate")
	public String getJoiningDate() {
		return joiningDate;
	}

	public void setJoiningDate(String joiningDate) {
		this.joiningDate = joiningDate;
	}

	@DynamoDBIndexHashKey(attributeName = "departmentId", globalSecondaryIndexName = "departmentId-index")
	public String getDepartment() {
		return department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	@DynamoDBAttribute(attributeName = "registeredCourses")
	public Set<String> getRegisteredCourses() {
		return registeredCourses;// the courseid set
	}

	public void setRegisteredCourses(Set<String> registeredCourses) {
		this.registeredCourses = registeredCourses;
	}

	@DynamoDBIndexHashKey(attributeName = "studentId", globalSecondaryIndexName = "studentId-index")
	public String getStudentId() {
		return studentId;
	}

	public void setStudentId(String studentId) {
		this.studentId = studentId;
	}

	@DynamoDBAttribute(attributeName = "image")
	public String getImage() {
		return image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@DynamoDBIgnore
	@Override
	public String toString() {
		return "Name: " + firstName + " " + lastName + "  StudentId: " + studentId + "   " + id;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	// @DynamoDBAttribute(attributeName = "imageURL") // i dont know

}
